#!/bin/bash
clear
readonly ru=$(dirname $(readlink -f "$0"))
source $ru/disig
apt install mdk4
apt install aircrack-ng
chmod ugo+x $ru/language/ru
chmod ugo+x $ru/language/en
chmod ugo+x $ru/wkbye
chmod ugo+x $ru/source/source
chmod ugo+x $ru/help/helpru
chmod ugo+x $ru/help/helpen
clear
